# Generated by Django 4.1.6 on 2023-02-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WatchList_app', '0002_streamplatform_watchlist_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='WatchList_app.streamplatform'),
            preserve_default=False,
        ),
    ]
